steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package', '-Dmaven.test.skip=true']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/aic-enterprises/aic-enterprise', '--build-arg=JAR_FILE=target/aic-enterprise.jar', '.']
images: ['gcr.io/aic-enterprises/aic-enterprise']
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '--image-url=gcr.io/aic-enterprises/aic-enterprise']