server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Actuator configurations
#health:
#  diskspace:
#    enabled: false
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  health:
    diskSpace:
      enabled: false

spring:
  data:
    mongodb:
      uri: 'mongodb+srv://aic_admin:D%40mnpassword1%21@aic-cluster.ihdn0.gcp.mongodb.net/aic-group?retryWrites=true&w=majority'
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: aic.enterprises9@gmail.com
#    password: ENC(n7CJIEJ/K0K0wPzyhq2vWrVSlD6lGT9041uAFzPX9O0=)
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#          starttls:
#            enable: true
  resources:
    cache:
      cachecontrol:
        max-age: 31536000

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    password: supersecretkey

java:
  security:
    edg: 'file:/dev/./urandom'

sendgrid:
  apikey: ENC(WQM1RnqE2RzIeIHwxeFyE5lStDuV7whJ5Z373vWz6Azepf+OPRvXKNCpVPEu+8BX1qFOCPlfYgSxL4piLd4WKDyWhgTLRkxOrg8HVImk/q8=)

cloudinary:
  apiKey: ENC(Gl9dDD0H5JwJZVXLg3k73E1t9IKWQvo0)
  apiSecret: ENC(7kLh4hii9fF+DnDRZpyPqYkPfFhDpYkT6IAW+eSFZb7N2oiBz6twZw==)