spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: aic.enterprises9@gmail.com
    password: ENC(qF3GrO9vp9kmWTlMM912PzQ44qU4IqX/)
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  resources:
    cache:
      cachecontrol:
        max-age: 31536000

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

sendgrid:
  apikey: ENC(IdUHaO4lI9tBC3GFdq2yQ8eaWUh63F+YjkteX3fT1YApEEFd0plFXQdZlgfH15op8H1ipzUQ/NpMbM7zf3k2fEzC8C4TyGec3icfdBJNcmM=)