  export const productData = {
  'Thermo Fisher Scientific': 'Thermo Fisher Scientific is a chain of companies in Life Sciences with the mission to make the world healthier, cleaner and safer. The staff and scientists here believe Thermo Fisher Scientific INC is “The World Leader in Serving Science” and they rightly do so by supporting their clients in accelerating life sciences research, solving complex analytical challenges, improving patient diagnostics and therapies or increasing productivity in their laboratories. The global team delivers an unrivaled combination of innovative technologies, purchasing convenience and pharmaceutical services through their industry-leading brands, including Thermo Scientific, Applied Biosystems, Invitrogen, Fisher Scientific, Unity Lab Services and Patheon.',
  'SRL': 'Sisco Research Laboratories Pvt. Ltd. is the renowned chemical industry, spreading it’s domain over the production of Research Chemicals in India since 1975. SRL has pioneered in manufacturing and marketing the purest and high complex Chemical Reagents & Biochemicals in bulk, ranging 5000+ products to R&D Institutions, industries and universities. Categorically the products are general lab chemicals & solvents, media supplements & kits, DNA & Protein tools, Nanotechnology products and many more.',
  'AXIVA': 'Axiva Sichem Biotech Pvt. Ltd. is a product speciality company expertised in manufacturing, marketing and servicing the state-of-the-art laboratory instrumentation. This firm contributes to the science by rending fundamental Lab Filtrations, Glasswares, Instruments and Plastic Wares at highly economical prices. The products from Axiva come with a full-package including product updation, sertilization, technical application support, after sales service, maintenance calls, etc., making it the best choice for collaboration.',
  'RIVIERA': 'Riviera is a South-Africa based pure pharmaceutical company that supplies drugs, medical equipment, healthcare products and wellness kits to its consumers around the globe. Riviera is one of the largely prescribed drug companies by several medical professionals in India and has shown reliable results over the time.',
  'Merck': 'Merck is a leading science technology company operating across the verticals of healthcare, life science and performance materials. Started off as a pharmaceutical company in 1967, Merck India has come a long way developing high quality products in all the three domains for the welfare of the humankind. Scientific exploration and responsible entrepreneurship have been key to the Merck’s business, scientific and technological advancements.',
  'Qiagen': 'Qiagen is one of the popular firms in life sciences. Mission of Qiagen is to deliver Sample to Insight solutions enabling customers to unlock valuable molecular insights faster, better and more efficiently – from the raw biological sample to the final interpreted result. Qiagen is committed to making improvements in life possible by creating global relationships across the continuum from research in the life sciences, to molecular diagnostics and public safety applications in everyday use.',
  'Eutech': 'Eutech, a sister firm of Thermo Fisher Scientific INC, is dedicated to design and manufacture ASIC (Application Specific Integrated Circuits) sensor based water analysis instruments for laboratory and field requirements. Eutech products range from compact pocket testers & handheld meters to research-grade benchtop meters & industrial process controllers. The unique comprehensive product line of Eutech is known for its sensor technology, software programming and product design.',
  'VAI-Veltek': 'The main motto of VAI-Veltek Associates INC. is to design and formulate innovative solutions to address the control of particulate and microbial containment in the pharmaceutical, biotechnological and healthcare industry. The containment control product divisions offered are cleaners, sporicides, detergents, dispensing systems, sterile lubricants & waters, disinfectant sprays etc. VAI also offers a unique and specialized value-added advantage for its clientele known as Aseptic Processing INC, a consulting and training service.',
  'MagGenome': 'MagGeonome is a self-explanatory title adopted by an extraordinary firm working to develop nucleic acid extraction and purification kits by using magnetic nanotechnology. The company has developed two prime products -  XpressDNA (DNA extraction kit) and XpressAffinity (affinity resins kits). It also focuses on harnessing magnetic nanoparticles to create rational solutions in diagnosis, therapeutics and environmental remediations.',
  'Waters': 'Waters, The Science of What’s Possible, makes it a service based enterprise in the field of advanced science and technology ranging from biopharmaceuticals to food to environment to forensic toxicology and so on. The services offered by Waters are majorly of three types -  Compliance, Software and Instruments. Waters Corporation is the world\'s leading specialty measurement company focused on improving human health and well-being through the application of high-value analytical technologies and industry leading scientific expertise.',
  'Tarsons': 'Tarsons Products Pvt. Ltd is India’s leading laboratory accessories company producing and supplying lab equipment that are disposable or reusable. With years of experience and dint of it’s competence, Tarsons has manufactured diversified products -  centrifuge ware, cryo labware, tissue culture ware, liquid handling systems, safety products & instruments, etc. Tarson is expertised in Plastic Molding, manufactures outstanding products that are in sync with latest incentives and technologies.',
  'genaxy': 'Genaxy Scientific Pvt. Ltd. is one of the most promising laboratory apparatus across the verticals of life sciences. The tagline "Generation Next in Biotechnology" perfectly satisfies company’s innovation, quality, presence and growth all across the borders. From pipette tips to complex electrophoresis equipment, Genaxy has mastered it all and is known for its best result output.',
  'GE': 'GE Healthcare Pvt. Ltd., a leading global medical technology and life sciences company. GE provides a broad portfolio of products, solutions and services used in the diagnosis, treatment and monitoring of patients and in the development and manufacture of biopharmaceuticals. The healthcare system at GE offers medical technologies, digital infrastructure, decision support tools, data analytics to the professionals and on the sidelines provide education, training, consulting, services and accessories to the welfare of mankind.',
  'Borosil': 'Borosil Ltd is one of the listed companies in India. Its domain of interest is production of Industrial and Engineering Apparatus for diversified usage by the customers, which enjoys the patronage of millions as on today. It is a classic in the scientific glass producing industry and has developed equipment with lasting worth.',
  'Honeywell': 'Honeywell is a multinational conglomerate company operating across the verticals from aerospace to safety & productivity solutions. Narrowing down to health and pharma, Honeywell aims for “Making it easier to help patients and for the people who care for them”. This industry is actively involved in research, 100+ years of innovation, manufacturing, supply chain and service in the Healthcare and Pharma Industry.',
  'HPLC (Thermo Fisher)': 'High Performance Liquid Chromatography is a complex yet extensively used device in the life sciences, agriculture, food, medical, chemical and pharmaceutical industry. It is an advanced chromatography technique wherein a solvent analyte is administered under high pressure for the isolation, extraction, detection or analysis. Thermo Fisher manufacturers HPLC Instruments and its respective units, hence consumed by institutions and industries hailing from academia and R&D.',
  'Sterimed Inc.': 'STERIMED INC. are pioneer suppliers in Sterilization Packaging, Monitoring Controls, Cleaning Chemistries and Teaching Aids in India. We are providing our dedicated services to various Hospitals, Scientific Research Institutes, Pharmaceutical Manufacturers and other Industries in India.',
  'Invitrogen': 'Invitrogen is one of a few brands under the Thermo Fisher Scientific company. Invitrogen Corporation gives items and administrations that help scholarly and government explore organizations and pharmaceutical and biotech organizations worldwide in their endeavors to improve the human condition.',
  'Kimberly-Clark': 'Kimberly-Clark Corporation, incorporated on June 29, 1928, is engaged in the manufacturing and marketing of a range of products made from natural or synthetic fibers. The Company’s segments include Personal Care, Consumer Tissue, K-C Professional and Corporate & Other.'
}

export const productTabsData = {
  'Thermo Fisher Scientific': ['Thermo TPP', 'Thermo Invitrogen', 'Thermo Orion', 'Thermo oxoid', 'Thermo chromatography', 'Thermo CCP', 'Thermo LPE', 'Fisher Scientific', 'Fisher Bio Reagents', 'Fisherbrand'],
  'Honeywell': ['Honeywell Safety Products', 'Honeywell-Chemicals'],
  'Borosil': ['Beakers', 'Bottles', 'Burettes (Class A)', 'Burettes (Class B)', 'Columns', 'Condensors', 'Cylinders (class A)', 'Cylinders (class B )', 'Dessicators', 'Dishes', 'Dissolution flasks', 'Distilling apparatus', 'Extractors', 'Filter assembly', 'Flask (joint others)', 'Flask (plain)', 'Funnels', 'Jars', 'Lab quest', 'LHS', 'Petroleum Jar', 'Pipettes (Class A)', 'Pipettes (Class B)', 'Quartz ware', 'Test tubes', 'Tubes', 'Vials', 'Volumetric Flask (Class A)', 'Volumetric Flask (Class B)', 'Others']
}

export const productTabsDataAll = ['Thermo TPP', 'Thermo Invitrogen', 'Thermo Orion', 'Thermo oxoid', 'Thermo chromatography', 'Thermo CCP', 'Thermo LPE', 'Fisher Scientific', 'Fisher Bio Reagents', 'Fisherbrand'];