  export const productData = {
  'Thermo Fisher Scientific': 'Thermo Fisher Scientific is a chain of companies in Life Sciences with the mission to make the world healthier, cleaner and safer. The staff and scientists here believe Thermo Fisher Scientific INC is “The World Leader in Serving Science” and they rightly do so by supporting their clients in accelerating life sciences research, solving complex analytical challenges, improving patient diagnostics and therapies or increasing productivity in their laboratories. The global team delivers an unrivaled combination of innovative technologies, purchasing convenience and pharmaceutical services through their industry-leading brands, including Thermo Scientific, Applied Biosystems, Invitrogen, Fisher Scientific, Unity Lab Services and Patheon.',
  'SRL': 'Sisco Research Laboratories Pvt. Ltd. is the renowned chemical industry, spreading it’s domain over the production of Research Chemicals in India since 1975. SRL has pioneered in manufacturing and marketing the purest and high complex Chemical Reagents & Biochemicals in bulk, ranging 5000+ products to R&D Institutions, industries and universities. Categorically the products are general lab chemicals & solvents, media supplements & kits, DNA & Protein tools, Nanotechnology products and many more.',
  'AXIVA': 'Axiva Sichem Biotech Pvt. Ltd. is a product speciality company expertised in manufacturing, marketing and servicing the state-of-the-art laboratory instrumentation. This firm contributes to the science by rending fundamental Lab Filtrations, Glasswares, Instruments and Plastic Wares at highly economical prices. The products from Axiva come with a full-package including product updation, sertilization, technical application support, after sales service, maintenance calls, etc., making it the best choice for collaboration.',
  'RIVIERA': 'Riviera is a South-Africa based pure pharmaceutical company that supplies drugs, medical equipment, healthcare products and wellness kits to its consumers around the globe. Riviera is one of the largely prescribed drug companies by several medical professionals in India and has shown reliable results over the time.',
  'Merck': 'Merck is a leading science technology company operating across the verticals of healthcare, life science and performance materials. Started off as a pharmaceutical company in 1967, Merck India has come a long way developing high quality products in all the three domains for the welfare of the humankind. Scientific exploration and responsible entrepreneurship have been key to the Merck’s business, scientific and technological advancements.',
  'Merck Biomonitoring': 'Merck is a leading science technology company operating across the verticals of healthcare, life science and performance materials. Started off as a pharmaceutical company in 1967, Merck India has come a long way developing high quality products in all the three domains for the welfare of the humankind. Scientific exploration and responsible entrepreneurship have been key to the Merck’s business, scientific and technological advancements.',
  'Qiagen': 'Qiagen is one of the popular firms in life sciences. Mission of Qiagen is to deliver Sample to Insight solutions enabling customers to unlock valuable molecular insights faster, better and more efficiently – from the raw biological sample to the final interpreted result. Qiagen is committed to making improvements in life possible by creating global relationships across the continuum from research in the life sciences, to molecular diagnostics and public safety applications in everyday use.',
  'Eutech': 'Eutech, a sister firm of Thermo Fisher Scientific INC, is dedicated to design and manufacture ASIC (Application Specific Integrated Circuits) sensor based water analysis instruments for laboratory and field requirements. Eutech products range from compact pocket testers & handheld meters to research-grade benchtop meters & industrial process controllers. The unique comprehensive product line of Eutech is known for its sensor technology, software programming and product design.',
  'VAI-Veltek': 'The main motto of VAI-Veltek Associates INC. is to design and formulate innovative solutions to address the control of particulate and microbial containment in the pharmaceutical, biotechnological and healthcare industry. The containment control product divisions offered are cleaners, sporicides, detergents, dispensing systems, sterile lubricants & waters, disinfectant sprays etc. VAI also offers a unique and specialized value-added advantage for its clientele known as Aseptic Processing INC, a consulting and training service.',
  'MagGenome': 'MagGeonome is a self-explanatory title adopted by an extraordinary firm working to develop nucleic acid extraction and purification kits by using magnetic nanotechnology. The company has developed two prime products -  XpressDNA (DNA extraction kit) and XpressAffinity (affinity resins kits). It also focuses on harnessing magnetic nanoparticles to create rational solutions in diagnosis, therapeutics and environmental remediations.',
  'Waters': 'Waters, The Science of What’s Possible, makes it a service based enterprise in the field of advanced science and technology ranging from biopharmaceuticals to food to environment to forensic toxicology and so on. The services offered by Waters are majorly of three types -  Compliance, Software and Instruments. Waters Corporation is the world\'s leading specialty measurement company focused on improving human health and well-being through the application of high-value analytical technologies and industry leading scientific expertise.',
  'Tarsons': 'Tarsons Products Pvt. Ltd is India’s leading laboratory accessories company producing and supplying lab equipment that are disposable or reusable. With years of experience and dint of it’s competence, Tarsons has manufactured diversified products -  centrifuge ware, cryo labware, tissue culture ware, liquid handling systems, safety products & instruments, etc. Tarson is expertised in Plastic Molding, manufactures outstanding products that are in sync with latest incentives and technologies.',
  'Genaxy': 'Genaxy Scientific Pvt. Ltd. is one of the most promising laboratory apparatus across the verticals of life sciences. The tagline "Generation Next in Biotechnology" perfectly satisfies company’s innovation, quality, presence and growth all across the borders. From pipette tips to complex electrophoresis equipment, Genaxy has mastered it all and is known for its best result output.',
  'GE': 'GE Healthcare Pvt. Ltd., a leading global medical technology and life sciences company. GE provides a broad portfolio of products, solutions and services used in the diagnosis, treatment and monitoring of patients and in the development and manufacture of biopharmaceuticals. The healthcare system at GE offers medical technologies, digital infrastructure, decision support tools, data analytics to the professionals and on the sidelines provide education, training, consulting, services and accessories to the welfare of mankind.',
  'Borosil': 'Borosil Ltd is one of the listed companies in India. Its domain of interest is production of Industrial and Engineering Apparatus for diversified usage by the customers, which enjoys the patronage of millions as on today. It is a classic in the scientific glass producing industry and has developed equipment with lasting worth.',
  'Honeywell': 'Honeywell is a multinational conglomerate company operating across the verticals from aerospace to safety & productivity solutions. Narrowing down to health and pharma, Honeywell aims for “Making it easier to help patients and for the people who care for them”. This industry is actively involved in research, 100+ years of innovation, manufacturing, supply chain and service in the Healthcare and Pharma Industry.',
  'HPLC (Thermo Fisher)': 'High Performance Liquid Chromatography is a complex yet extensively used device in the life sciences, agriculture, food, medical, chemical and pharmaceutical industry. It is an advanced chromatography technique wherein a solvent analyte is administered under high pressure for the isolation, extraction, detection or analysis. Thermo Fisher manufacturers HPLC Instruments and its respective units, hence consumed by institutions and industries hailing from academia and R&D.',
  'Sterimed Inc.': 'STERIMED INC. are pioneer suppliers in Sterilization Packaging, Monitoring Controls, Cleaning Chemistries and Teaching Aids in India. We are providing our dedicated services to various Hospitals, Scientific Research Institutes, Pharmaceutical Manufacturers and other Industries in India.',
  'Invitrogen': 'Invitrogen is one of a few brands under the Thermo Fisher Scientific company. Invitrogen Corporation gives items and administrations that help scholarly and government explore organizations and pharmaceutical and biotech organizations worldwide in their endeavors to improve the human condition.',
  'Kimberly-Clark': 'Kimberly-Clark Corporation, incorporated on June 29, 1928, is engaged in the manufacturing and marketing of a range of products made from natural or synthetic fibers. The Company’s segments include Personal Care, Consumer Tissue, K-C Professional and Corporate & Other.',
  '3M': '3M offers products and solutions worldwide through Industrial & Water Business Unit and Life Sciences & Integration Business, including Biopharmaceutical Purification, Medical & Industrial Membranes and Polymer Additives. It has been in the business for over 90 years and provides high quality filtration products to address challenging filtration processes in the Water, Industrial and Biopharmaceutical markets.',
  'Abdos': 'Abdos Labtech Private Limited is a manufacturer of high quality plastic laboratory products. Since inception it has been prototyping, designing, developing and manufacturing high quality plastic products used in life science laboratories around the world. In addition to plastics it also markets a large variety of bench top instruments and products for safety & utilities for use in the laboratory.',
  'Dupont': 'DuPont Nutrition & Biosciences applies expert science to advance healthy and sustainable products for the food, beverage, dietary supplement and pharmaceutical industries. Also uses pioneering biotechnology to enable bio-based solutions that make industrial processes more efficient and sustainable.',
  'Acme': 'ACME Medical Technology was established in 2012 with highly experienced professionals in the Medical Field. ACME is an Important player in the field of Laser Surgery & focuses on Quality of life of patients who benefit from ACME\'s Technology. It provides the best quality products like Surgical Lasers for Stone & Prostate, Urodynamics & Uroflowmetry System, ESWL , Mono-Polar & Bi-Polar Cautery System from a Reputed Manufacturer.',
  'Blue Star': 'Blue Star Limited, a USD 681 million engineering conglomerate headquartered in India. Deals in advanced technologies to supply products, solutions, and services related to the Healthcare Systems line of business, to help create a healthy society. The company represents Hitachi Healthcare of Japan in India, for their range of medical diagnostic imaging systems such as MRI and CT, with advanced imaging technology, sophisticated interfaces and data analysis techniques.',
  'Erma': 'Erma Inc. is one of the leading manufacturers of medical and diagnostic equipment in the world; the  pioneers in Colorimeter. With the technical expertise and experience of 100 plus years it is manufacturing Hematology, Clinical Chemistry and Electrolyte Analyzers, Microtomes, Pathocutter, Bilirubin and Bilirubin with Hematocrit mainly designed for Neonate samples, Digital Hemoglobin Meter, Refractometers.',
  'Exmire': 'Exmire company was founded in 1980 as a specialized producer of Microsyringes. Now, manufactures and sells not only Microsyringes, but also other products for the aspiration and discharge of liquids and gases, from pipes to nozzles.',
  'HAMILTON': 'Hamilton Company has been a leading global manufacturer for more than 60 years. The Company specializes in the development, manufacturing and customization of precision measurement devices, automated liquid handling workstations, and sample management systems.',
  'NEB': 'Founded in the mid-1970s as a collective of scientists committed to developing innovative products for the life sciences industry, New England Biolabs (NEB) is now a recognized world leader in the discovery and production of enzymes for molecular biology applications.',
  'NICE': 'Nice chemicals was established in 1976 . At present NICE manufactures around 1500 products of various ranges like Laboratory reagents, Analytical reagents, Biochemicals, IP/USP chemicals, HPLC solvents, Indicator powders, solutions, soil/water testing kits, Agro chemicals and Laboratory Glass wares. NICE has also made its presence in the clinical laboratory field through Nice Diagnostic Centres.',
  'LOBA': 'Founded in 1973 as a fine chemical manufacturer, Loba Chemie has grown into a customer-focused global supplier of high quality chemicals, laboratory supplies and equipment.',
  'Whatman': 'Whatman products cover a range of laboratory applications that require filtration, sample collection (cards and kits), blotting, lateral flow components and flow-through assays and other general laboratory accessories. Formerly Whatman plc, the company was originally acquired in 2008 by GE Healthcare, which became Cytiva in April 2020.',
  'HIMEDIA': 'With a presence in more than 140 countries HiMedia is amongst the top three brands in microbiology in the world. It possesses world-class hi-tech know-how for manufacturing a complete range of chromogenic and HiVeg™ media products. This Company produces a comprehensive range of Plant and Animal based hydrolysates; advanced products in the fields of Animal Cell Culture, Plant Tissue Culture and Molecular Biology. HiMedia delivers consistent ultra-pure products.',
  'Nupore': 'Incorporated in 1989, Nupore Filtration System (NFS) is a fast growing company dedicated to research, development & production of Glass Microfiber Filters, Micro Porous Membranes, Diagnostic Kit Products & various related products. Offers a wide range of Membranes for fine filtration of liquids as well as Diagnostic applications.',
  'Millipore': 'Merck Millipore provides scientists and engineers with best-in-class lab materials, technologies and services. With the 2015 combination of Merck Millipore and Sigma-Aldrich, it now has a broad portfolio of 300,000 products, an expanded global footprint and is fully dedicated to making research and biotech production simpler, faster and safer.',
  'Spectrochem': 'As pioneers of HPLC since 1984, Spectrochem offers the largest and most expansive range of HPLC and GC Grade solvents in the country. Has aligned with industries across the board, including: pharmaceuticals, agrochemicals, space research, life sciences and biotechnology.',
  'Polylab': 'PolyLab Industries Pvt. Ltd is one of the leading manufacturers of a sizable range of Plastic Labware in India. With the versatility to manufacture world class plastic labware products, it caters to different branches of science, including general, molecular biology, cell culture, and more. Polylab International, a group company of Polylab Inds. Pvt.Ltd also manufactures pharmaceutical packaging containers and closures.',
  'Difco': 'Difco Laboratories Incorporated is a manufacturer of medical equipment. The Company produces diagnostic and medical instruments. It manufactures and sells a broad range of diagnostic systems, medical instruments, supplies and devices for the use of health care professionals, medical research institutions and the general public.',
  'CDH': 'CDH has been serving the scientific community with the largest range of Laboratory Fine Chemicals & Dehydrated Culture Media since 1981. CDH is presently manufacturing and marketing over 9000 products. The best combination of Bio chemicals, Research Chemicals, Laboratory Reagents, HPLC/AAS/EL/DRY Solvents, Stains & Indicators and Dehydrated Culture Media is offered by the company.'
}

export const productTabsData = {
  'Thermo Fisher Scientific': ['Thermo TPP', 'Thermo Invitrogen', 'Thermo Orion', 'Thermo oxoid', 'Thermo chromatography', 'Thermo CCP', 'Thermo LPE', 'Fisher Scientific', 'Fisher Bio Reagents', 'Fisherbrand'],
  'Honeywell': ['Honeywell Safety Products', 'Honeywell-Chemicals'],
  'Borosil': ['Beakers', 'Bottles', 'Burettes (Class A)', 'Burettes (Class B)', 'Columns', 'Condensors', 'Cylinders (class A)', 'Cylinders (class B )', 'Dessicators', 'Dishes', 'Dissolution flasks', 'Distilling apparatus', 'Extractors', 'Filter assembly', 'Flask (joint others)', 'Flask (plain)', 'Funnels', 'Jars', 'Lab quest', 'LHS', 'Petroleum Jar', 'Pipettes (Class A)', 'Pipettes (Class B)', 'Quartz ware', 'Test tubes', 'Tubes', 'Vials', 'Volumetric Flask (Class A)', 'Volumetric Flask (Class B)', 'Others']
}

export const productTabsDataAll = ['Thermo TPP', 'Thermo Invitrogen', 'Thermo Orion', 'Thermo oxoid', 'Thermo chromatography', 'Thermo CCP', 'Thermo LPE', 'Fisher Scientific', 'Fisher Bio Reagents', 'Fisherbrand'];