export const brandList = [
  {name: 'Abdos', imageName: 'abdos'}, 
  {name: 'AXIVA', imageName: 'Axiva-Logo'}, 
  // {name: 'CDH', imageName: ''}, TODO: add later
  {name: 'Conda', imageName: 'conda'}, 
  {name: 'Dupont', imageName: 'DuPont'}, 
  {name: 'Difco', imageName: 'DIFCO'}, 
  {name: 'Eutech', imageName: 'eutech'}, 
  {name: 'Exmire', imageName: 'exmire_logo_w300'}, 
  // {name: 'Thermo TPP', imageName: 'ThermoScientific-Tag'}, 
  {name: 'Invitrogen', imageName: 'invitrogen-vector-logo'}, 
  // {name: 'Orion', imageName: 'orion-1-logo-png-transparent'}, 
  // {name: 'Oxoid', imageName: 'OXOID'}, 
  // {name: 'Thermo chromatography', imageName: 'ThermoScientific-Tag'}, 
  // {name: 'Thermo LPE', imageName: 'ThermoScientific-Tag'}, 
  {name: 'Thermo Fisher Scientific', imageName: 'ThermoScientific-Tag'}, 
  // {name: 'Fisher Bio Reagents', imageName: 'Fisher-BioReagents_800x800'}, 
  // {name: 'Fisherbrand', imageName: 'fisherbrand'}, 
  {name: 'Genaxy', imageName: 'genaxy'}, 
  {name: 'HAMILTON', imageName: 'hamilton'}, 
  {name: 'HIMEDIA', imageName: 'himedia'}, 
  {name: 'Honeywell', imageName: 'honeywell-vector-logo'}, 
  {name: 'Kimberly-Clark', imageName: 'Kim'}, 
  {name: 'LOBA', imageName: 'loba-chemie-500x500'}, 
  {name: 'MagGenome', imageName: 'maggeneme'}, 
  {name: 'Merck', imageName: 'merck'}, 
  {name: 'SIGMA-ALDRICH', imageName: 'Sigma-Aldrich'}, 
  {name: 'Millipore', imageName: 'Millipore_Corporation_Logo.svg'}, 
  {name: 'NEB', imageName: 'NEB'}, 
  // {name: 'NICE', imageName: 'NICE'}, TODO: add later
  {name: 'Nupore', imageName: 'nupore-logo-cropped'}, 
  {name: 'Polylab', imageName: 'polylab'}, 
  {name: 'Qiagen', imageName: '1200px-Qiagen.svg'}, 
  {name: 'Reagecon', imageName: 'reagecon'}, 
  {name: 'RIVIERA', imageName: 'Riviera_logo'}, 
  {name: 'Spectrochem', imageName: 'S'}, 
  {name: 'SRL', imageName: 'SRL_Diagnostics_Logo'}, 
  {name: 'Waters', imageName: 'Waters-Logo-Header'}, 
  {name: 'Whatman', imageName: 'whatman-logo'}
]